### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/cachito-archives/bundles/1.tar.gz'

### ISSUE THREAD

**Issue by lcarva** [release-engineering/cachito#126]
On a clean local environment, submitting the example request from `README.md` fails.

```
🐚  git rev-parse HEAD
8672b8b04af92cf761d4d256559c50c3bf81738f

🐚  docker-compose down -v
Removing network cachito_default
WARNING: Network cachito_default not found.
Removing volume cachito_nexus-volume
WARNING: Volume cachito_nexus-volume not found.
lucarval@localhost ~/src/exd/osbs-guild/cachito 

🐚  docker-compose up
...

🐚  curl -X POST -H "Content-Type: application/json" http://localhost:8080/api/v1/requests -d \
>         '{
>            "repo": "https://github.com/release-engineering/retrodep.git",
>            "ref": "e1be527f39ec31323f0454f7d1422c6260b00580",
>            "pkg_managers": ["gomod"]
>          }'
{
  "dependencies": [], 
  "environment_variables": {}, 
  "flags": [], 
  "id": 1, 
  "packages": [], 
  "pkg_managers": [
    "gomod"
  ], 
  "ref": "e1be527f39ec31323f0454f7d1422c6260b00580", 
  "repo": "https://github.com/release-engineering/retrodep.git", 
  "state": "in_progress", 
  "state_history": [
    {
      "state": "in_progress", 
      "state_reason": "The request was initiated", 
      "updated": "2020-04-02T17:18:03.671757"
    }
  ], 
  "state_reason": "The request was initiated", 
  "submitted_by": null, 
  "updated": "2020-04-02T17:18:03.671757", 
  "user": null
}
```
The request is marked as failed. The cachito-worker logs contain the following traceback:
```
cachito-worker_1  | [2020-04-02 17:18:03,739: INFO/ForkPoolWorker-1] Fetching the source from "https://github.com/release-engineering/retrodep.git" at reference "e1be527f39ec31323f0454f7d1422c6260b00580"
cachito-worker_1  | [2020-04-02 17:18:03,792: INFO/ForkPoolWorker-1] Setting the state of request 1 to "in_progress" with the reason "Fetching the application source"
cachito-worker_1  | [2020-04-02 17:18:03,826: DEBUG/ForkPoolWorker-1] Parsed the repository name "release-engineering/retrodep" from https://github.com/release-engineering/retrodep.git
cachito-worker_1  | [2020-04-02 17:18:03,826: DEBUG/ForkPoolWorker-1] Ensure directory /tmp/cachito-archives/sources/release-engineering/retrodep exists.
cachito-worker_1  | [2020-04-02 17:18:03,828: DEBUG/ForkPoolWorker-1] Cloning the Git repository from https://github.com/release-engineering/retrodep.git
cachito-worker_1  | [2020-04-02 17:18:04,297: DEBUG/ForkPoolWorker-1] Creating the archive at /tmp/cachito-archives/sources/release-engineering/retrodep/e1be527f39ec31323f0454f7d1422c6260b00580.tar.gz
cachito-worker_1  | [2020-04-02 17:18:04,380: DEBUG/ForkPoolWorker-1] Ensure directory /tmp/cachito-archives/bundles/temp/1 exists.
cachito-worker_1  | [2020-04-02 17:18:04,380: DEBUG/ForkPoolWorker-1] Ensure directory /tmp/cachito-archives/bundles/temp/1/deps exists.
cachito-worker_1  | [2020-04-02 17:18:04,381: DEBUG/ForkPoolWorker-1] Extracting /tmp/cachito-archives/bundles/1.tar.gz to /tmp/cachito-archives/bundles/temp/1
cachito-worker_1  | [2020-04-02 17:18:04,383: INFO/ForkPoolWorker-1] Setting the state of request 1 to "failed" with the reason "An unknown error occurred"
cachito-worker_1  | [2020-04-02 17:18:04,406: ERROR/ForkPoolWorker-1] Task cachito.workers.tasks.general.fetch_app_source[12ce8686-f53a-4649-b8e8-08cefbf937d3] raised unexpected: FileNotFoundError(2, 'No such file or directory')
cachito-worker_1  | Traceback (most recent call last):
cachito-worker_1  |   File "/usr/lib/python3.7/site-packages/celery/app/trace.py", line 385, in trace_task
cachito-worker_1  |     R = retval = fun(*args, **kwargs)
cachito-worker_1  |   File "/usr/lib/python3.7/site-packages/celery/app/trace.py", line 648, in __protected_call__
cachito-worker_1  |     return self.run(*args, **kwargs)
cachito-worker_1  |   File "/src/cachito/workers/tasks/general.py", line 50, in fetch_app_source
cachito-worker_1  |     extract_app_src(bundle_dir.bundle_archive_file, str(bundle_dir))
cachito-worker_1  |   File "/src/cachito/workers/utils.py", line 15, in extract_app_src
cachito-worker_1  |     with tarfile.open(archive_path, "r:*") as archive:
cachito-worker_1  |   File "/usr/lib64/python3.7/tarfile.py", line 1573, in open
cachito-worker_1  |     return func(name, "r", fileobj, **kwargs)
cachito-worker_1  |   File "/usr/lib64/python3.7/tarfile.py", line 1638, in gzopen
cachito-worker_1  |     fileobj = gzip.GzipFile(name, mode + "b", compresslevel, fileobj)
cachito-worker_1  |   File "/usr/lib64/python3.7/gzip.py", line 163, in __init__
cachito-worker_1  |     fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
cachito-worker_1  | FileNotFoundError: [Errno 2] No such file or directory: '/tmp/cachito-archives/bundles/1.tar.gz'

```

**Comment by lcarva** [comment]
Potentially related to 34313b94533848174737c4bf0a8508ce26510739

**Comment by mprahl** [comment]
This patch works for me locally but haven't fixed the unit tests yet:
```diff
diff --git a/cachito/workers/tasks/general.py b/cachito/workers/tasks/general.py
index 8459f4a..2929332 100644
--- a/cachito/workers/tasks/general.py
+++ b/cachito/workers/tasks/general.py
@@ -47,7 +47,7 @@ def fetch_app_source(url, ref, request_id):
     # some package managers may add dependency replacements, which require edits to source files.
     bundle_dir = RequestBundleDir(request_id)
     log.debug("Extracting %s to %s", bundle_dir.bundle_archive_file, bundle_dir)
-    extract_app_src(bundle_dir.bundle_archive_file, str(bundle_dir))
+    extract_app_src(scm.sources_dir.archive_path, str(bundle_dir))
 
 
 @app.task
```

**Comment by athos-ribeiro** [comment]
This was fixed by https://github.com/release-engineering/cachito/pull/129.

@lcarva can you confirm this before we close this one?
